#!/bin/bash
# AUTOGENERATED SCRIPT
# This script will import all categories into your Terraform state
# for the deploymenttheory/jamfpro provider.

echo "--- Starting Terraform import for categories ---"

# Initialize a counter for successes
success_count=0
total_count=0

# Define a function to run import and check for errors
run_import() {
    let total_count+=1
    echo "Importing: $1 (ID: $2)"
    if terraform import "$1" "$2"; then
        let success_count+=1
    else
        echo "⚠️  Warning: Failed to import $1 (ID: $2). It may already be in your state."
    fi
}

run_import 'jamfpro_category.accounting__finance' 36741
run_import 'jamfpro_category.aerospace' 36838
run_import 'jamfpro_category.engineering' 36831
run_import 'jamfpro_category.facilities' 36837
run_import 'jamfpro_category.finance' 36830
run_import 'jamfpro_category.hr' 36829
run_import 'jamfpro_category.legal' 36836
run_import 'jamfpro_category.marketing' 36832
run_import 'jamfpro_category.nannas_house' 36833
run_import 'jamfpro_category.operations' 36834
run_import 'jamfpro_category.security' 36835
run_import 'jamfpro_category.team1_ai__machine_learning' 36726
run_import 'jamfpro_category.team1_application_management' 36743
run_import 'jamfpro_category.team1_architecture__design' 36747
run_import 'jamfpro_category.team1_asset_management' 36682
run_import 'jamfpro_category.team1_automation__orchestration' 36681
run_import 'jamfpro_category.team1_billing__payments' 36692
run_import 'jamfpro_category.team1_brand__marketing' 36679
run_import 'jamfpro_category.team1_business_continuity' 36701
run_import 'jamfpro_category.team1_change_management' 36745
run_import 'jamfpro_category.team1_client_relationship_management' 36686
run_import 'jamfpro_category.team1_cloud_infrastructure' 36694
run_import 'jamfpro_category.team1_communication__collaboration' 36727
run_import 'jamfpro_category.team1_compliance__audit' 36685
run_import 'jamfpro_category.team1_content_management' 36714
run_import 'jamfpro_category.team1_customer_experience' 36717
run_import 'jamfpro_category.team1_customer_support' 36678
run_import 'jamfpro_category.team1_cybersecurity' 36716
run_import 'jamfpro_category.team1_data_analytics' 36724
run_import 'jamfpro_category.team1_data_management' 36710
run_import 'jamfpro_category.team1_data_privacy' 36721
run_import 'jamfpro_category.team1_data_warehousing' 36711
run_import 'jamfpro_category.team1_devops__cicd' 36730
run_import 'jamfpro_category.team1_digital_experience' 36722
run_import 'jamfpro_category.team1_digital_transformation' 36706
run_import 'jamfpro_category.team1_disaster_recovery' 36732
run_import 'jamfpro_category.team1_e_commerce' 36696
run_import 'jamfpro_category.team1_engineering__rd' 36736
run_import 'jamfpro_category.team1_enterprise_applications' 36746
run_import 'jamfpro_category.team1_environmental_sustainability' 36691
run_import 'jamfpro_category.team1_field_operations' 36715
run_import 'jamfpro_category.team1_financial_operations' 36683
run_import 'jamfpro_category.team1_governance__risk' 36742
run_import 'jamfpro_category.team1_hardware__devices' 36703
run_import 'jamfpro_category.team1_human_resources' 36684
run_import 'jamfpro_category.team1_identity__access_management' 36723
run_import 'jamfpro_category.team1_infrastructure_operations' 36729
run_import 'jamfpro_category.team1_integration_services' 36739
run_import 'jamfpro_category.team1_internal_tools' 36720
run_import 'jamfpro_category.team1_it_governance' 36737
run_import 'jamfpro_category.team1_it_operations' 36738
run_import 'jamfpro_category.team1_knowledge_management' 36704
run_import 'jamfpro_category.team1_legal__compliance' 36707
run_import 'jamfpro_category.team1_licensing__entitlements' 36733
run_import 'jamfpro_category.team1_logistics__supply_chain' 36705
run_import 'jamfpro_category.team1_monitoring__observability' 36740
run_import 'jamfpro_category.team1_networking__connectivity' 36713
run_import 'jamfpro_category.team1_performance_optimization' 36734
run_import 'jamfpro_category.team1_platform_engineering' 36731
run_import 'jamfpro_category.team1_procurement__vendor_management' 36708
run_import 'jamfpro_category.team1_product_management' 36748
run_import 'jamfpro_category.team1_project_management' 36675
run_import 'jamfpro_category.team1_quality_assurance__testing' 36719
run_import 'jamfpro_category.team1_release_management' 36700
run_import 'jamfpro_category.team1_remote_work__collaboration' 36749
run_import 'jamfpro_category.team1_reporting__insights' 36712
run_import 'jamfpro_category.team1_research__innovation' 36709
run_import 'jamfpro_category.team1_resource_planning' 36725
run_import 'jamfpro_category.team1_sales_operations' 36728
run_import 'jamfpro_category.team1_security_operations' 36695
run_import 'jamfpro_category.team1_server_management' 36702
run_import 'jamfpro_category.team1_service_management' 36676
run_import 'jamfpro_category.team1_site_reliability_engineering' 36735
run_import 'jamfpro_category.team1_software_development' 36718
run_import 'jamfpro_category.team1_storage__backup' 36688
run_import 'jamfpro_category.team1_strategic_planning' 36697
run_import 'jamfpro_category.team1_talent_acquisition' 36744
run_import 'jamfpro_category.team1_technical_support' 36687
run_import 'jamfpro_category.team1_training__development' 36677
run_import 'jamfpro_category.team1_user_experience__design' 36689
run_import 'jamfpro_category.team1_user_support__operations' 36693
run_import 'jamfpro_category.team1_vendor_management' 36690
run_import 'jamfpro_category.team1_workflow_automation' 36699
run_import 'jamfpro_category.team1_workplace_technology' 36680
run_import 'jamfpro_category.testing_gd' 36669

echo ""
echo "--- ✅ Import complete. ---"
echo "$success_count / $total_count categories successfully imported."
