# -----------------------------------------------
# AUTOGENERATED FILE - DO NOT EDIT MANUALLY
# Provider: deploymenttheory/jamfpro
# Run 'generate_terraform_config.sh' to refresh.
# -----------------------------------------------

resource "jamfpro_category" "accounting__finance" {
  name     = "Accounting & Finance"
  priority = 12
}

resource "jamfpro_category" "aerospace" {
  name     = "Aerospace"
  priority = 9
}

resource "jamfpro_category" "engineering" {
  name     = "Engineering"
  priority = 9
}

resource "jamfpro_category" "facilities" {
  name     = "Facilities"
  priority = 9
}

resource "jamfpro_category" "finance" {
  name     = "Finance"
  priority = 9
}

resource "jamfpro_category" "hr" {
  name     = "HR"
  priority = 9
}

resource "jamfpro_category" "legal" {
  name     = "Legal"
  priority = 9
}

resource "jamfpro_category" "marketing" {
  name     = "Marketing"
  priority = 9
}

resource "jamfpro_category" "nannas_house" {
  name     = "Nannas house"
  priority = 9
}

resource "jamfpro_category" "operations" {
  name     = "Operations"
  priority = 9
}

resource "jamfpro_category" "security" {
  name     = "Security"
  priority = 9
}

resource "jamfpro_category" "team1_ai__machine_learning" {
  name     = "AI & Machine Learning"
  priority = 6
}

resource "jamfpro_category" "team1_application_management" {
  name     = "Application Management"
  priority = 8
}

resource "jamfpro_category" "team1_architecture__design" {
  name     = "Architecture & Design"
  priority = 10
}

resource "jamfpro_category" "team1_asset_management" {
  name     = "Asset Management"
  priority = 13
}

resource "jamfpro_category" "team1_automation__orchestration" {
  name     = "Automation & Orchestration"
  priority = 13
}

resource "jamfpro_category" "team1_billing__payments" {
  name     = "Billing & Payments"
  priority = 12
}

resource "jamfpro_category" "team1_brand__marketing" {
  name     = "Brand & Marketing"
  priority = 19
}

resource "jamfpro_category" "team1_business_continuity" {
  name     = "Business Continuity"
  priority = 19
}

resource "jamfpro_category" "team1_change_management" {
  name     = "Change Management"
  priority = 14
}

resource "jamfpro_category" "team1_client_relationship_management" {
  name     = "Client Relationship Management"
  priority = 10
}

resource "jamfpro_category" "team1_cloud_infrastructure" {
  name     = "Cloud Infrastructure"
  priority = 4
}

resource "jamfpro_category" "team1_communication__collaboration" {
  name     = "Communication & Collaboration"
  priority = 8
}

resource "jamfpro_category" "team1_compliance__audit" {
  name     = "Compliance & Audit"
  priority = 16
}

resource "jamfpro_category" "team1_content_management" {
  name     = "Content Management"
  priority = 11
}

resource "jamfpro_category" "team1_customer_experience" {
  name     = "Customer Experience"
  priority = 9
}

resource "jamfpro_category" "team1_customer_support" {
  name     = "Customer Support"
  priority = 7
}

resource "jamfpro_category" "team1_cybersecurity" {
  name     = "Cybersecurity"
  priority = 1
}

resource "jamfpro_category" "team1_data_analytics" {
  name     = "Data Analytics"
  priority = 5
}

resource "jamfpro_category" "team1_data_management" {
  name     = "Data Management"
  priority = 6
}

resource "jamfpro_category" "team1_data_privacy" {
  name     = "Data Privacy"
  priority = 2
}

resource "jamfpro_category" "team1_data_warehousing" {
  name     = "Data Warehousing"
  priority = 4
}

resource "jamfpro_category" "team1_devops__cicd" {
  name     = "DevOps & CI/CD"
  priority = 5
}

resource "jamfpro_category" "team1_digital_experience" {
  name     = "Digital Experience"
  priority = 8
}

resource "jamfpro_category" "team1_digital_transformation" {
  name     = "Digital Transformation"
  priority = 10
}

resource "jamfpro_category" "team1_disaster_recovery" {
  name     = "Disaster Recovery"
  priority = 18
}

resource "jamfpro_category" "team1_e_commerce" {
  name     = "E-Commerce"
  priority = 17
}

resource "jamfpro_category" "team1_engineering__rd" {
  name     = "Engineering & R&D"
  priority = 6
}

resource "jamfpro_category" "team1_enterprise_applications" {
  name     = "Enterprise Applications"
  priority = 11
}

resource "jamfpro_category" "team1_environmental_sustainability" {
  name     = "Environmental Sustainability"
  priority = 18
}

resource "jamfpro_category" "team1_field_operations" {
  name     = "Field Operations"
  priority = 16
}

resource "jamfpro_category" "team1_financial_operations" {
  name     = "Financial Operations"
  priority = 13
}

resource "jamfpro_category" "team1_governance__risk" {
  name     = "Governance & Risk"
  priority = 15
}

resource "jamfpro_category" "team1_hardware__devices" {
  name     = "Hardware & Devices"
  priority = 14
}

resource "jamfpro_category" "team1_human_resources" {
  name     = "Human Resources"
  priority = 20
}

resource "jamfpro_category" "team1_identity__access_management" {
  name     = "Identity & Access Management"
  priority = 1
}

resource "jamfpro_category" "team1_infrastructure_operations" {
  name     = "Infrastructure Operations"
  priority = 5
}

resource "jamfpro_category" "team1_integration_services" {
  name     = "Integration Services"
  priority = 9
}

resource "jamfpro_category" "team1_internal_tools" {
  name     = "Internal Tools"
  priority = 7
}

resource "jamfpro_category" "team1_it_governance" {
  name     = "IT Governance"
  priority = 15
}

resource "jamfpro_category" "team1_it_operations" {
  name     = "IT Operations"
  priority = 4
}

resource "jamfpro_category" "team1_knowledge_management" {
  name     = "Knowledge Management"
  priority = 8
}

resource "jamfpro_category" "team1_legal__compliance" {
  name     = "Legal & Compliance"
  priority = 16
}

resource "jamfpro_category" "team1_licensing__entitlements" {
  name     = "Licensing & Entitlements"
  priority = 11
}

resource "jamfpro_category" "team1_logistics__supply_chain" {
  name     = "Logistics & Supply Chain"
  priority = 14
}

resource "jamfpro_category" "team1_monitoring__observability" {
  name     = "Monitoring & Observability"
  priority = 3
}

resource "jamfpro_category" "team1_networking__connectivity" {
  name     = "Networking & Connectivity"
  priority = 3
}

resource "jamfpro_category" "team1_performance_optimization" {
  name     = "Performance Optimization"
  priority = 9
}

resource "jamfpro_category" "team1_platform_engineering" {
  name     = "Platform Engineering"
  priority = 5
}

resource "jamfpro_category" "team1_procurement__vendor_management" {
  name     = "Procurement & Vendor Management"
  priority = 12
}

resource "jamfpro_category" "team1_product_management" {
  name     = "Product Management"
  priority = 10
}

resource "jamfpro_category" "team1_project_management" {
  name     = "Project Management"
  priority = 13
}

resource "jamfpro_category" "team1_quality_assurance__testing" {
  name     = "Quality Assurance & Testing"
  priority = 9
}

resource "jamfpro_category" "team1_release_management" {
  name     = "Release Management"
  priority = 7
}

resource "jamfpro_category" "team1_remote_work__collaboration" {
  name     = "Remote Work & Collaboration"
  priority = 8
}

resource "jamfpro_category" "team1_reporting__insights" {
  name     = "Reporting & Insights"
  priority = 10
}

resource "jamfpro_category" "team1_research__innovation" {
  name     = "Research & Innovation"
  priority = 11
}

resource "jamfpro_category" "team1_resource_planning" {
  name     = "Resource Planning"
  priority = 12
}

resource "jamfpro_category" "team1_sales_operations" {
  name     = "Sales Operations"
  priority = 13
}

resource "jamfpro_category" "team1_security_operations" {
  name     = "Security Operations"
  priority = 1
}

resource "jamfpro_category" "team1_server_management" {
  name     = "Server Management"
  priority = 4
}

resource "jamfpro_category" "team1_service_management" {
  name     = "Service Management"
  priority = 6
}

resource "jamfpro_category" "team1_site_reliability_engineering" {
  name     = "Site Reliability Engineering"
  priority = 3
}

resource "jamfpro_category" "team1_software_development" {
  name     = "Software Development"
  priority = 7
}

resource "jamfpro_category" "team1_storage__backup" {
  name     = "Storage & Backup"
  priority = 9
}

resource "jamfpro_category" "team1_strategic_planning" {
  name     = "Strategic Planning"
  priority = 15
}

resource "jamfpro_category" "team1_talent_acquisition" {
  name     = "Talent Acquisition"
  priority = 18
}

resource "jamfpro_category" "team1_technical_support" {
  name     = "Technical Support"
  priority = 8
}

resource "jamfpro_category" "team1_training__development" {
  name     = "Training & Development"
  priority = 9
}

resource "jamfpro_category" "team1_user_experience__design" {
  name     = "User Experience & Design"
  priority = 10
}

resource "jamfpro_category" "team1_user_support__operations" {
  name     = "User Support & Operations"
  priority = 17
}

resource "jamfpro_category" "team1_vendor_management" {
  name     = "Vendor Management"
  priority = 13
}

resource "jamfpro_category" "team1_workflow_automation" {
  name     = "Workflow Automation"
  priority = 6
}

resource "jamfpro_category" "team1_workplace_technology" {
  name     = "Workplace Technology"
  priority = 7
}

resource "jamfpro_category" "testing_gd" {
  name     = "testing-gd"
  priority = 9
}

